sudo: false
dist: trusty
language: c

addons:
  apt:
    packages:
      - libc6-i386
      - make

install:
  - curl -L https://launchpad.net/gcc-arm-embedded/4.9/4.9-2015-q3-update/+download/gcc-arm-none-eabi-4_9-2015q3-20150921-linux.tar.bz2 | tar xjf -
  - export PATH="$PWD/gcc-arm-none-eabi-4_9-2015q3/bin:$PATH"

script:
  - CFLAGS="-std=c99" make -C vendor/libopencm3
  - make
  - make -C firmware
  - make -C bootloader
  - make -C fastflash
  - make -C demo
  - make -C firmware clean && make -C firmware FASTFLASH=1

notifications:
  webhooks:
    urls:
      - http://ci-bot.satoshilabs.com:5000/travis
    on_success: always
    on_failure: always
    on_start: always
