sudo: false
dist: trusty
language: c

addons:
  apt:
    packages:
      - build-essential
      - gcc-arm-none-eabi
      - libnewlib-arm-none-eabi

env:
  global:
    - MAKEFLAGS=-j2
    - PROTOBUF_VERSION=3.4.0
  matrix:
    - DEBUG_LINK=0 FASTFLASH=0
    - DEBUG_LINK=1 FASTFLASH=0
    - DEBUG_LINK=0 FASTFLASH=1
    - DEBUG_LINK=1 FASTFLASH=1

matrix:
  include:
    - addons:
        apt:
          packages:
            - gcc-multilib
      env:
        - EMULATOR=1 HEADLESS=1
        - DEBUG_LINK=1
      before_script:
        - sed -i '/hidapi/d' "vendor/python-trezor/requirements.txt"
        - pip install --user --requirement "vendor/python-trezor/requirements.txt" rlp pytest requests[security]
        - pip install --user --no-deps "vendor/python-trezor"
      script:
        - script/cibuild
        - script/test

install:
  - curl -LO "https://github.com/google/protobuf/releases/download/v${PROTOBUF_VERSION}/protoc-${PROTOBUF_VERSION}-linux-x86_64.zip"
  - unzip "protoc-${PROTOBUF_VERSION}-linux-x86_64.zip" -d protoc
  - export PATH="$(pwd)/protoc/bin:$PATH"
  - pip2 install --user "protobuf==${PROTOBUF_VERSION}"

script:
  - script/cibuild
  - make -C bootloader
  - make -C demo

notifications:
  webhooks:
    urls:
      - http://ci-bot.satoshilabs.com:5000/travis
    on_success: always
    on_failure: always
    on_start: always
