sudo: false
dist: trusty
language: c

git:
  submodules: false

before_install:
  - vendor/travis-submodules

addons:
  apt:
    packages:
    - build-essential
    - git
    - gcc-arm-none-eabi
    - libnewlib-arm-none-eabi

script:
  - CFLAGS="-std=c99" make -C vendor/libopencm3
  - make
  - make -C bootloader
  - make -C fastflash
  - make -C firmware
  - make -C demo
  - make -C firmware clean && make -C firmware FASTFLASH=1

notifications:
  webhooks:
    urls:
      - http://ci-bot.satoshilabs.com:5000/travis
    on_success: always
    on_failure: always
    on_start: always
